name: Tests

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - run: pnpm lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        with:
          run_install: true
      - run: pnpm typecheck

  # spelling:
  #   name: Spelling
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v7
  #     - uses: actions/setup-node@v7
  #       with:
  #         node-version: 24
  #     - uses: pnpm/action-setup@v6
  #       with:
  #         run_install: true
  #     - run: pnpm spelling
